openapi: 3.0.0
info:
  title: Content Service API
  version: 1.0.0
  description: API to manage film and actor entities.
servers:
  - url: http://localhost:8080/api
    description: main local server

paths:
  /films:
    get:
      summary: Return a list of all available films.
      responses:
        '200':
          description: list of films.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Film'
    post:
      summary: Add a new film
      requestBody:
        description: add film details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film'
      responses:
        '201':
          description: Film added with successfully
        '400':
          description: Error request (missing data)

  /films/{id}:
    get:
      summary: Return information about specific film.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details of specific film
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        '404':
          description: Film not found
          
    put:
      summary: Aggiorna le informazioni di un film
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Dettagli del film aggiornati
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film'
      responses:
        '200':
          description: Film aggiornato con successo
        '400':
          description: Richiesta errata
        '404':
          description: Film non trovato

    patch:
      summary: Aggiorna parzialmente le informazioni di un film
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Dettagli del film da aggiornare parzialmente
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film'
      responses:
        '200':
          description: Film aggiornato con successo
        '400':
          description: Richiesta errata
        '404':
          description: Film non trovato

    delete:
      summary: Cancella un film specifico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Film cancellato con successo
        '404':
          description: Film non trovato

components:
  schemas:
    Film:
      type: object
      properties:
        id:
          type: integer
          description: Film's ID
          example: 1
        title:
          type: string
          description: Film's title
          example: "Il Padrino"
        Actors:
          type: string
          description: actors in the films
          example: "Al Pacino, James Caan"
        release_year:
          type: integer
          description: year of release
          example: 1972
        genre:
          type: string
          description: type of film
          example: "Drammatico"
        rating:
          type: number
          description: film's rating (from 1 to 10)
          example: 9.2
